---
swagger: "2.0"
info:
  description: "api counter"
  version: "1.0"
  title: "api counter"
basePath: "/stage"
schemes:
- "https"
paths:
  /api:
    get:
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            content-security-policy:
              type: "string"
            x-xss-protection:
              type: "string"
            x-content-type-options:
              type: "string"
            Access-Control-Allow-Origin:
              type: "string"
            x-frame-options:
              type: "string"
            referrer-policy:
              type: "string"
            strict-transport-security:
              type: "string"
      x-amazon-apigateway-integration:
        type: "aws"
        httpMethod: "POST"
        uri: "${function_arn}"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.referrer-policy: "'same-origin'"
              method.response.header.x-xss-protection: "''1; mode=block''"
              method.response.header.x-content-type-options: "'nosniff'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
              method.response.header.content-security-policy: "'default-src 'none';\
                \ img-src 'self'; script-src 'self'; style-src 'self'; object-src\
                \ 'none''"
              method.response.header.x-frame-options: "'DENY'"
              method.response.header.strict-transport-security: "'max-age=63072000;\
                \ includeSubdomains; preload'"
        passthroughBehavior: "when_no_templates"
        contentHandling: "CONVERT_TO_TEXT"
    options:
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/Empty"
          headers:
            Access-Control-Allow-Origin:
              type: "string"
            Access-Control-Allow-Methods:
              type: "string"
            Access-Control-Allow-Headers:
              type: "string"
      x-amazon-apigateway-integration:
        type: "mock"
        responses:
          default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Origin: "'*'"
        requestTemplates:
          application/json: "{\"statusCode\": 200}"
        passthroughBehavior: "when_no_match"
definitions:
  Empty:
    type: "object"
    title: "Empty Schema"
